# Generated by Django 4.2.7 on 2025-06-03 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('auto_scan_enabled', models.BooleanField(default=True)),
                ('scan_interval', models.IntegerField(default=300)),
                ('scan_range', models.CharField(default='192.168.1.0/24', max_length=100)),
                ('traffic_monitoring', models.BooleanField(default=True)),
                ('security_monitoring', models.BooleanField(default=True)),
                ('packet_capture', models.BooleanField(default=False)),
                ('alert_on_new_devices', models.BooleanField(default=True)),
                ('alert_on_device_offline', models.BooleanField(default=True)),
                ('alert_on_port_scan', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('computer', 'Computer'), ('mobile', 'Mobile Device'), ('printer', 'Printer'), ('iot', 'IoT Device'), ('server', 'Server'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('os_info', models.TextField(blank=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('is_monitored', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('port_scan', 'Port Scan Detected'), ('unusual_traffic', 'Unusual Traffic Pattern'), ('new_device', 'New Device Detected'), ('device_offline', 'Device Went Offline'), ('failed_connection', 'Failed Connection Attempts'), ('suspicious_activity', 'Suspicious Activity')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events_as_source', to='network_monitor.networkdevice')),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events_as_target', to='network_monitor.networkdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=36, unique=True)),
                ('scan_type', models.CharField(choices=[('ping', 'Ping Scan'), ('port', 'Port Scan'), ('full', 'Full Scan'), ('discovery', 'Device Discovery')], max_length=20)),
                ('target_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('devices_found', models.IntegerField(default=0)),
                ('ports_scanned', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('is_active', models.BooleanField(default=True)),
                ('interface_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('active_connections', models.IntegerField(default=0)),
                ('bandwidth_usage', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='network_monitor.networkdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('device', 'timestamp')},
            },
        ),
    ]
