# Generated by Django 4.2.7 on 2025-06-03 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='avg_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='current_bandwidth_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='is_scanning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='last_ping_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='last_port_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='monitor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='packet_loss_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ping_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ping_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='scan_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='security_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='services_running',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='total_bytes_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='total_bytes_out',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='total_downtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='uptime_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='vulnerability_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('uptime_at_time', models.FloatField(default=0.0)),
                ('packet_loss_at_time', models.FloatField(default=0.0)),
                ('trigger_event', models.CharField(choices=[('ping_success', 'Ping Success'), ('ping_failure', 'Ping Failure'), ('port_scan', 'Port Scan'), ('traffic_analysis', 'Traffic Analysis'), ('manual_check', 'Manual Check'), ('system_startup', 'System Startup')], default='ping_success', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='network_monitor.networkdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='network_mon_device__a87aa9_idx'), models.Index(fields=['timestamp'], name='network_mon_timesta_b708c1_idx')],
            },
        ),
    ]
