# Generated by Django 4.2.7 on 2025-06-04 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network_monitor', '0002_networkdevice_avg_response_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('scan_type', models.CharField(choices=[('ping_sweep', 'Ping Sweep'), ('port_scan', 'Port Scan'), ('service_detection', 'Service Detection'), ('os_fingerprinting', 'OS Fingerprinting'), ('vulnerability_scan', 'Vulnerability Scan'), ('discovery', 'Network Discovery'), ('stealth_scan', 'Stealth Scan'), ('comprehensive', 'Comprehensive Scan'), ('custom', 'Custom Scan')], max_length=30)),
                ('default_ports', models.CharField(blank=True, max_length=1000)),
                ('scan_techniques', models.JSONField(blank=True, default=list)),
                ('timing_template', models.CharField(default='normal', max_length=20)),
                ('service_detection', models.BooleanField(default=True)),
                ('version_detection', models.BooleanField(default=False)),
                ('os_detection', models.BooleanField(default=False)),
                ('script_scanning', models.BooleanField(default=False)),
                ('max_parallel_hosts', models.IntegerField(default=50)),
                ('timeout_per_host', models.IntegerField(default=30)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='networkscan',
            old_name='devices_found',
            new_name='hosts_down',
        ),
        migrations.RenameField(
            model_name='networkscan',
            old_name='ports_scanned',
            new_name='hosts_up',
        ),
        migrations.RenameField(
            model_name='networkscan',
            old_name='results',
            new_name='metadata',
        ),
        migrations.AddField(
            model_name='networkscan',
            name='aggressive_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='auto_retry_on_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='bandwidth_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='cpu_usage_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkscan',
            name='current_phase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='current_target',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='debug_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='exclude_hosts',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='fragment_packets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='generate_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='host_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='max_auto_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='max_parallel_hosts',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='max_parallel_ports',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='memory_usage_peak',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='open_ports_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='os_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='port_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('critical', 'Critical Priority')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='randomize_hosts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='report_format',
            field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('pdf', 'PDF'), ('html', 'HTML')], default='json', max_length=20),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='scan_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='scan_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='scan_techniques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='schedule_cron',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='script_scanning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='service_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='service_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='services_detected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='spoof_source_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='target_ports',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='timeout_per_host',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='timing_template',
            field=models.CharField(choices=[('paranoid', 'Paranoid (T0)'), ('sneaky', 'Sneaky (T1)'), ('polite', 'Polite (T2)'), ('normal', 'Normal (T3)'), ('aggressive', 'Aggressive (T4)'), ('insane', 'Insane (T5)')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='total_hosts_scanned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='total_ports_scanned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='version_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='vulnerabilities_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='vulnerability_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='scan_type',
            field=models.CharField(choices=[('ping_sweep', 'Ping Sweep'), ('port_scan', 'Port Scan'), ('service_detection', 'Service Detection'), ('os_fingerprinting', 'OS Fingerprinting'), ('vulnerability_scan', 'Vulnerability Scan'), ('discovery', 'Network Discovery'), ('stealth_scan', 'Stealth Scan'), ('comprehensive', 'Comprehensive Scan'), ('custom', 'Custom Scan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initializing', 'Initializing'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='target_range',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='networkscan',
            index=models.Index(fields=['status', '-started_at'], name='network_mon_status_7c5e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='networkscan',
            index=models.Index(fields=['scan_type', '-started_at'], name='network_mon_scan_ty_7a724f_idx'),
        ),
        migrations.AddIndex(
            model_name='networkscan',
            index=models.Index(fields=['started_by', '-started_at'], name='network_mon_started_70a078_idx'),
        ),
        migrations.AddIndex(
            model_name='networkscan',
            index=models.Index(fields=['priority', '-started_at'], name='network_mon_priorit_aa69f5_idx'),
        ),
        migrations.AddField(
            model_name='scantemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
